// Code generated by dgw. DO NOT EDIT.

package dgwexample

import (
	"context"
	"database/sql"
	"time"

	"github.com/pkg/errors"
)

// T1 represents public.t1
type T1 struct {
	ID          int64          // id
	I           int            // i
	Str         string         // str
	NumFloat    float64        // num_float
	NullableStr sql.NullString // nullable_str
	TWithTz     time.Time      // t_with_tz
	TWithoutTz  time.Time      // t_without_tz
	NullableTz  *time.Time     // nullable_tz
	JSONData    []byte         // json_data
	XMLData     []byte         // xml_data
}

// Create inserts the T1 to the database.
//
// Deprecated: Use CreateContext instead.
func (r *T1) Create(db Queryer) error {
	return r.CreateContext(context.Background(), db)
}

// GetT1ByPk select the T1 from the database.
//
// Deprecated: Use GetT1ByPkContext instead.
func GetT1ByPk(db Queryer, pk0 int64) (*T1, error) {
	return GetT1ByPkContext(context.Background(), db, pk0)
}

// CreateContext inserts the T1 to the database.
func (r *T1) CreateContext(ctx context.Context, db Queryer) error {
	err := db.QueryRowContext(ctx,
		`INSERT INTO t1 (i, str, num_float, nullable_str, t_with_tz, t_without_tz, nullable_tz, json_data, xml_data) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id`,
		&r.I, &r.Str, &r.NumFloat, &r.NullableStr, &r.TWithTz, &r.TWithoutTz, &r.NullableTz, &r.JSONData, &r.XMLData).Scan(&r.ID)
	if err != nil {
		return errors.WithStack(err)
	}
	return nil
}

// CreateOnConflictDoNothing inserts the T1 to the database.
// If a conflict occurs (e.g., unique constraint violation), the insert is skipped without error.
// Returns true if the row was inserted, false if it was skipped due to conflict.
func (r *T1) CreateOnConflictDoNothing(ctx context.Context, db Queryer) (bool, error) {
	err := db.QueryRowContext(ctx,
		`INSERT INTO t1 (i, str, num_float, nullable_str, t_with_tz, t_without_tz, nullable_tz, json_data, xml_data) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) ON CONFLICT DO NOTHING RETURNING id`,
		&r.I, &r.Str, &r.NumFloat, &r.NullableStr, &r.TWithTz, &r.TWithoutTz, &r.NullableTz, &r.JSONData, &r.XMLData).Scan(&r.ID)
	if err != nil {
		if err == sql.ErrNoRows {
			return false, nil
		}
		return false, errors.WithStack(err)
	}
	// Row was successfully inserted
	return true, nil
}

// GetT1ByPkContext select the T1 from the database.
func GetT1ByPkContext(ctx context.Context, db Queryer, pk0 int64) (*T1, error) {
	var r T1
	err := db.QueryRowContext(ctx,
		`SELECT id, i, str, num_float, nullable_str, t_with_tz, t_without_tz, nullable_tz, json_data, xml_data FROM t1 WHERE id = $1`,
		pk0).Scan(&r.ID, &r.I, &r.Str, &r.NumFloat, &r.NullableStr, &r.TWithTz, &r.TWithoutTz, &r.NullableTz, &r.JSONData, &r.XMLData)
	if err != nil {
		return nil, errors.WithStack(err)
	}
	return &r, nil
}

// T2 represents public.t2
type T2 struct {
	ID         int64     // id
	I          int       // i
	Str        string    // str
	TWithTz    time.Time // t_with_tz
	TWithoutTz time.Time // t_without_tz
}

// Create inserts the T2 to the database.
//
// Deprecated: Use CreateContext instead.
func (r *T2) Create(db Queryer) error {
	return r.CreateContext(context.Background(), db)
}

// GetT2ByPk select the T2 from the database.
//
// Deprecated: Use GetT2ByPkContext instead.
func GetT2ByPk(db Queryer, pk0 int64, pk1 int) (*T2, error) {
	return GetT2ByPkContext(context.Background(), db, pk0, pk1)
}

// CreateContext inserts the T2 to the database.
func (r *T2) CreateContext(ctx context.Context, db Queryer) error {
	err := db.QueryRowContext(ctx,
		`INSERT INTO t2 (str, t_with_tz, t_without_tz) VALUES ($1, $2, $3) RETURNING id, i`,
		&r.Str, &r.TWithTz, &r.TWithoutTz).Scan(&r.ID, &r.I)
	if err != nil {
		return errors.WithStack(err)
	}
	return nil
}

// CreateOnConflictDoNothing inserts the T2 to the database.
// If a conflict occurs (e.g., unique constraint violation), the insert is skipped without error.
// Returns true if the row was inserted, false if it was skipped due to conflict.
func (r *T2) CreateOnConflictDoNothing(ctx context.Context, db Queryer) (bool, error) {
	err := db.QueryRowContext(ctx,
		`INSERT INTO t2 (str, t_with_tz, t_without_tz) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING RETURNING id, i`,
		&r.Str, &r.TWithTz, &r.TWithoutTz).Scan(&r.ID, &r.I)
	if err != nil {
		if err == sql.ErrNoRows {
			return false, nil
		}
		return false, errors.WithStack(err)
	}
	// Row was successfully inserted
	return true, nil
}

// GetT2ByPkContext select the T2 from the database.
func GetT2ByPkContext(ctx context.Context, db Queryer, pk0 int64, pk1 int) (*T2, error) {
	var r T2
	err := db.QueryRowContext(ctx,
		`SELECT id, i, str, t_with_tz, t_without_tz FROM t2 WHERE id = $1 AND i = $2`,
		pk0, pk1).Scan(&r.ID, &r.I, &r.Str, &r.TWithTz, &r.TWithoutTz)
	if err != nil {
		return nil, errors.WithStack(err)
	}
	return &r, nil
}

// T3 represents public.t3
type T3 struct {
	ID int // id
	I  int // i
}

// Create inserts the T3 to the database.
//
// Deprecated: Use CreateContext instead.
func (r *T3) Create(db Queryer) error {
	return r.CreateContext(context.Background(), db)
}

// GetT3ByPk select the T3 from the database.
//
// Deprecated: Use GetT3ByPkContext instead.
func GetT3ByPk(db Queryer, pk0 int, pk1 int) (*T3, error) {
	return GetT3ByPkContext(context.Background(), db, pk0, pk1)
}

// CreateContext inserts the T3 to the database.
func (r *T3) CreateContext(ctx context.Context, db Queryer) error {
	_, err := db.ExecContext(ctx,
		`INSERT INTO t3 (id, i) VALUES ($1, $2)`,
		&r.ID, &r.I)
	if err != nil {
		return errors.WithStack(err)
	}
	return nil
}

// CreateOnConflictDoNothing inserts the T3 to the database.
// If a conflict occurs (e.g., unique constraint violation), the insert is skipped without error.
// Returns true if the row was inserted, false if it was skipped due to conflict.
func (r *T3) CreateOnConflictDoNothing(ctx context.Context, db Queryer) (bool, error) {
	result, err := db.ExecContext(ctx,
		`INSERT INTO t3 (id, i) VALUES ($1, $2) ON CONFLICT DO NOTHING`,
		&r.ID, &r.I)
	if err != nil {
		return false, errors.WithStack(err)
	}
	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return false, errors.WithStack(err)
	}
	return rowsAffected > 0, nil
}

// GetT3ByPkContext select the T3 from the database.
func GetT3ByPkContext(ctx context.Context, db Queryer, pk0 int, pk1 int) (*T3, error) {
	var r T3
	err := db.QueryRowContext(ctx,
		`SELECT id, i FROM t3 WHERE id = $1 AND i = $2`,
		pk0, pk1).Scan(&r.ID, &r.I)
	if err != nil {
		return nil, errors.WithStack(err)
	}
	return &r, nil
}

// UserAccount represents public.user_account
type UserAccount struct {
	ID        int64  // id
	Email     string // email
	LastName  string // last_name
	FirstName string // first_name
}

// Create inserts the UserAccount to the database.
//
// Deprecated: Use CreateContext instead.
func (r *UserAccount) Create(db Queryer) error {
	return r.CreateContext(context.Background(), db)
}

// GetUserAccountByPk select the UserAccount from the database.
//
// Deprecated: Use GetUserAccountByPkContext instead.
func GetUserAccountByPk(db Queryer, pk0 int64) (*UserAccount, error) {
	return GetUserAccountByPkContext(context.Background(), db, pk0)
}

// CreateContext inserts the UserAccount to the database.
func (r *UserAccount) CreateContext(ctx context.Context, db Queryer) error {
	err := db.QueryRowContext(ctx,
		`INSERT INTO user_account (email, last_name, first_name) VALUES ($1, $2, $3) RETURNING id`,
		&r.Email, &r.LastName, &r.FirstName).Scan(&r.ID)
	if err != nil {
		return errors.WithStack(err)
	}
	return nil
}

// CreateOnConflictDoNothing inserts the UserAccount to the database.
// If a conflict occurs (e.g., unique constraint violation), the insert is skipped without error.
// Returns true if the row was inserted, false if it was skipped due to conflict.
func (r *UserAccount) CreateOnConflictDoNothing(ctx context.Context, db Queryer) (bool, error) {
	err := db.QueryRowContext(ctx,
		`INSERT INTO user_account (email, last_name, first_name) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING RETURNING id`,
		&r.Email, &r.LastName, &r.FirstName).Scan(&r.ID)
	if err != nil {
		if err == sql.ErrNoRows {
			return false, nil
		}
		return false, errors.WithStack(err)
	}
	// Row was successfully inserted
	return true, nil
}

// GetUserAccountByPkContext select the UserAccount from the database.
func GetUserAccountByPkContext(ctx context.Context, db Queryer, pk0 int64) (*UserAccount, error) {
	var r UserAccount
	err := db.QueryRowContext(ctx,
		`SELECT id, email, last_name, first_name FROM user_account WHERE id = $1`,
		pk0).Scan(&r.ID, &r.Email, &r.LastName, &r.FirstName)
	if err != nil {
		return nil, errors.WithStack(err)
	}
	return &r, nil
}

// UserAccountCompositePk represents public.user_account_composite_pk
type UserAccountCompositePk struct {
	ID        int64  // id
	Email     string // email
	LastName  string // last_name
	FirstName string // first_name
}

// Create inserts the UserAccountCompositePk to the database.
//
// Deprecated: Use CreateContext instead.
func (r *UserAccountCompositePk) Create(db Queryer) error {
	return r.CreateContext(context.Background(), db)
}

// GetUserAccountCompositePkByPk select the UserAccountCompositePk from the database.
//
// Deprecated: Use GetUserAccountCompositePkByPkContext instead.
func GetUserAccountCompositePkByPk(db Queryer, pk0 int64, pk1 string) (*UserAccountCompositePk, error) {
	return GetUserAccountCompositePkByPkContext(context.Background(), db, pk0, pk1)
}

// CreateContext inserts the UserAccountCompositePk to the database.
func (r *UserAccountCompositePk) CreateContext(ctx context.Context, db Queryer) error {
	_, err := db.ExecContext(ctx,
		`INSERT INTO user_account_composite_pk (id, email, last_name, first_name) VALUES ($1, $2, $3, $4)`,
		&r.ID, &r.Email, &r.LastName, &r.FirstName)
	if err != nil {
		return errors.WithStack(err)
	}
	return nil
}

// CreateOnConflictDoNothing inserts the UserAccountCompositePk to the database.
// If a conflict occurs (e.g., unique constraint violation), the insert is skipped without error.
// Returns true if the row was inserted, false if it was skipped due to conflict.
func (r *UserAccountCompositePk) CreateOnConflictDoNothing(ctx context.Context, db Queryer) (bool, error) {
	result, err := db.ExecContext(ctx,
		`INSERT INTO user_account_composite_pk (id, email, last_name, first_name) VALUES ($1, $2, $3, $4) ON CONFLICT DO NOTHING`,
		&r.ID, &r.Email, &r.LastName, &r.FirstName)
	if err != nil {
		return false, errors.WithStack(err)
	}
	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return false, errors.WithStack(err)
	}
	return rowsAffected > 0, nil
}

// GetUserAccountCompositePkByPkContext select the UserAccountCompositePk from the database.
func GetUserAccountCompositePkByPkContext(ctx context.Context, db Queryer, pk0 int64, pk1 string) (*UserAccountCompositePk, error) {
	var r UserAccountCompositePk
	err := db.QueryRowContext(ctx,
		`SELECT id, email, last_name, first_name FROM user_account_composite_pk WHERE id = $1 AND email = $2`,
		pk0, pk1).Scan(&r.ID, &r.Email, &r.LastName, &r.FirstName)
	if err != nil {
		return nil, errors.WithStack(err)
	}
	return &r, nil
}

// UserAccountUUID represents public.user_account_uuid
type UserAccountUUID struct {
	UUID      string // uuid
	Email     string // email
	LastName  string // last_name
	FirstName string // first_name
}

// Create inserts the UserAccountUUID to the database.
//
// Deprecated: Use CreateContext instead.
func (r *UserAccountUUID) Create(db Queryer) error {
	return r.CreateContext(context.Background(), db)
}

// GetUserAccountUUIDByPk select the UserAccountUUID from the database.
//
// Deprecated: Use GetUserAccountUUIDByPkContext instead.
func GetUserAccountUUIDByPk(db Queryer, pk0 string) (*UserAccountUUID, error) {
	return GetUserAccountUUIDByPkContext(context.Background(), db, pk0)
}

// CreateContext inserts the UserAccountUUID to the database.
func (r *UserAccountUUID) CreateContext(ctx context.Context, db Queryer) error {
	err := db.QueryRowContext(ctx,
		`INSERT INTO user_account_uuid (email, last_name, first_name) VALUES ($1, $2, $3) RETURNING uuid`,
		&r.Email, &r.LastName, &r.FirstName).Scan(&r.UUID)
	if err != nil {
		return errors.WithStack(err)
	}
	return nil
}

// CreateOnConflictDoNothing inserts the UserAccountUUID to the database.
// If a conflict occurs (e.g., unique constraint violation), the insert is skipped without error.
// Returns true if the row was inserted, false if it was skipped due to conflict.
func (r *UserAccountUUID) CreateOnConflictDoNothing(ctx context.Context, db Queryer) (bool, error) {
	err := db.QueryRowContext(ctx,
		`INSERT INTO user_account_uuid (email, last_name, first_name) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING RETURNING uuid`,
		&r.Email, &r.LastName, &r.FirstName).Scan(&r.UUID)
	if err != nil {
		if err == sql.ErrNoRows {
			return false, nil
		}
		return false, errors.WithStack(err)
	}
	// Row was successfully inserted
	return true, nil
}

// GetUserAccountUUIDByPkContext select the UserAccountUUID from the database.
func GetUserAccountUUIDByPkContext(ctx context.Context, db Queryer, pk0 string) (*UserAccountUUID, error) {
	var r UserAccountUUID
	err := db.QueryRowContext(ctx,
		`SELECT uuid, email, last_name, first_name FROM user_account_uuid WHERE uuid = $1`,
		pk0).Scan(&r.UUID, &r.Email, &r.LastName, &r.FirstName)
	if err != nil {
		return nil, errors.WithStack(err)
	}
	return &r, nil
}

// UserAccountUUIDAddress represents public.user_account_uuid_address
type UserAccountUUIDAddress struct {
	UUID  string // uuid
	State string // state
	City  string // city
	Line1 string // line1
	Line2 string // line2
}

// Create inserts the UserAccountUUIDAddress to the database.
//
// Deprecated: Use CreateContext instead.
func (r *UserAccountUUIDAddress) Create(db Queryer) error {
	return r.CreateContext(context.Background(), db)
}

// GetUserAccountUUIDAddressByPk select the UserAccountUUIDAddress from the database.
//
// Deprecated: Use GetUserAccountUUIDAddressByPkContext instead.
func GetUserAccountUUIDAddressByPk(db Queryer, pk0 string) (*UserAccountUUIDAddress, error) {
	return GetUserAccountUUIDAddressByPkContext(context.Background(), db, pk0)
}

// CreateContext inserts the UserAccountUUIDAddress to the database.
func (r *UserAccountUUIDAddress) CreateContext(ctx context.Context, db Queryer) error {
	_, err := db.ExecContext(ctx,
		`INSERT INTO user_account_uuid_address (uuid, state, city, line1, line2) VALUES ($1, $2, $3, $4, $5)`,
		&r.UUID, &r.State, &r.City, &r.Line1, &r.Line2)
	if err != nil {
		return errors.WithStack(err)
	}
	return nil
}

// CreateOnConflictDoNothing inserts the UserAccountUUIDAddress to the database.
// If a conflict occurs (e.g., unique constraint violation), the insert is skipped without error.
// Returns true if the row was inserted, false if it was skipped due to conflict.
func (r *UserAccountUUIDAddress) CreateOnConflictDoNothing(ctx context.Context, db Queryer) (bool, error) {
	result, err := db.ExecContext(ctx,
		`INSERT INTO user_account_uuid_address (uuid, state, city, line1, line2) VALUES ($1, $2, $3, $4, $5) ON CONFLICT DO NOTHING`,
		&r.UUID, &r.State, &r.City, &r.Line1, &r.Line2)
	if err != nil {
		return false, errors.WithStack(err)
	}
	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return false, errors.WithStack(err)
	}
	return rowsAffected > 0, nil
}

// GetUserAccountUUIDAddressByPkContext select the UserAccountUUIDAddress from the database.
func GetUserAccountUUIDAddressByPkContext(ctx context.Context, db Queryer, pk0 string) (*UserAccountUUIDAddress, error) {
	var r UserAccountUUIDAddress
	err := db.QueryRowContext(ctx,
		`SELECT uuid, state, city, line1, line2 FROM user_account_uuid_address WHERE uuid = $1`,
		pk0).Scan(&r.UUID, &r.State, &r.City, &r.Line1, &r.Line2)
	if err != nil {
		return nil, errors.WithStack(err)
	}
	return &r, nil
}
